### ISSUE TITLE
global variable

### ISSUE THREAD

**Issue by szagoruyko** [fmassa/object-detection.torch#1]
le petit garçon ici https://github.com/fmassa/object-detection.torch/blob/master/SPP.lua#L198 est global

**Comment by fmassa** [comment]
Really ? I though line https://github.com/fmassa/object-detection.torch/blob/master/SPP.lua#L181 would be enough to make it local. I'll check it tomorrow.

**Comment by szagoruyko** [comment]
no, another guy, this one _. had to be

``` lua
local _,bestScale
```

**Comment by fmassa** [comment]
Ah ok. It's true, I initially thought that the underscore symbol meant to ignore the return value. I'll fix that. Thanks Sergey !

**Comment by fmassa** [comment]
Fixed via https://github.com/fmassa/object-detection.torch/commit/cbe45d4a3921348fcc6953d74c1c87fdc6ebf574
