### ISSUE TITLE
Where or how can I get a 'model.t7'?

### ISSUE THREAD

**Issue by JirenJin** [fmassa/object-detection.torch#12]
In refactoring branch's README, there is an example that includes such code:

``` lua
model = torch.load('model.t7')
I = image.lena()
```

However, I cannot find  `model.t7`, could you please tell where or how to get it?

**Comment by fmassa** [comment]
Hi,
I will put those models online, but I still hadn't had the time to do it.
One way to get those models is to use [loadcaffe](https://github.com/szagoruyko/loadcaffe/) and use it to load the pre-trained models from RCNN or Fast-RCNN website.
I'll work on having some models available online soon.

**Comment by JirenJin** [comment]
@fmassa Thank you very much for your reply! I will try to use loadcaffe :)

**Comment by fmassa** [comment]
@jinjiren I've uploaded a pre-trained model for Fast-RCNN, and I've updated the README accordingly.
You can find it [here](https://drive.google.com/file/d/0B-TTdm1WNtyba3I4Vm1hbFRSS2c/view?usp=sharing).
