### ISSUE TITLE
The model cannot be downloaded 

### ISSUE THREAD

**Issue by aronfothi** [fmassa/object-detection.torch#14]

**Comment by aronfothi** [comment]
from https://drive.google.com/open?id=0B-TTdm1WNtybdzdMUHhLc05PSE0&authuser=0. The source cannot be read.

**Comment by fmassa** [comment]
Hum, weird. I just tried it in two different machines, and it worked just fine. Is Google Drive blocked in your country ?

**Comment by aronfothi** [comment]
Ok. I managed to download it today. It seems it was a temporal problem. Thanks.
