### ISSUE TITLE
Dead link to examples

### ISSUE THREAD

**Issue by Parry26** [fmassa/object-detection.torch#15]
The link provided for training examples:

https://github.com/fmassa/object-detection.torch/tree/master/examples

Is giving a 404 error.

**Comment by fmassa** [comment]
Yes, the link is dead because I added the link considering that I'd merge the `refactoring` branch soon (but I haven't...). The correct link is https://github.com/fmassa/object-detection.torch/tree/refactoring/examples
I'll change it in the README and update it when I merge it to master.

**Comment by fmassa** [comment]
Fixed in https://github.com/fmassa/object-detection.torch/commit/b949c6a5be0433ec8594e6b55fbb4c96635f41ab
Thanks !
