### ISSUE TITLE
How did you create the "frcnn_alexnet.t7" file?

### ISSUE THREAD

**Issue by liuchang8am** [fmassa/object-detection.torch#17]
I want to create a VGG16 network t7 file from pre-trained VGG16.caffemodel, how to create it, like the frcnn_alexnet.t7 you provided?

As you mention in #12 , use "loadcaffe" to load the pre-trained caffelmodel, yet loadcaffe does not support the ROIpooling layer in Fast-RCNN (-- warning: module 'roi_pool5 [type ROIPooling]' not found
 in generated .prototxt.lua file), how did you overcome this?

Thanks!

**Comment by szagoruyko** [comment]
converted models are here https://github.com/szagoruyko/fastrcnn-models.torch

**Comment by liuchang8am** [comment]
@szagoruyko thanks for the quick reply!

Actually, I still need to create the '.t7' model file myself, because I trained the VGG16 caffemodel task-specific. Could you please tell me how to create the file?

**Comment by szagoruyko** [comment]
loadcaffe will give you a sequential model that you can manually reorder too be as the ones in the link above. you will have to add inn.ROIPooling, check here https://github.com/szagoruyko/imagine-nn

**Comment by liuchang8am** [comment]
thanks! that's what I need!
