### ISSUE TITLE
can't run Examples in ReadMe 

### ISSUE THREAD

**Issue by liuchang8am** [fmassa/object-detection.torch#18]
The Examples script in ReadMe can't run with provided frcnn_alexnet.t7 (https://drive.google.com/file/d/0B-TTdm1WNtyba3I4Vm1hbFRSS2c/view?usp=sharing)  file. (refactoring branch)

 bin/luajit: models/frcnn_alexnet.lua:55: wrong number of parameter elements !
stack traceback:
        [C]: in function 'assert'
        models/frcnn_alexnet.lua:55: in function 'loadModel'
        test.lua:10: in main chunk
        [C]: in function 'dofile'
        ...e/lc/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by fmassa** [comment]
Thanks for pointing this out. Maybe a recent change in `nn` broke something.
I'll check that in 1h and I'll come back to you

**Comment by fmassa** [comment]
For the moment, `nn` doesn't support the `groups` option (which is necessary for alexnet model to run).
I'll update the README, but in the meanwhile, you can fix it by using the `cudnn` backend in loadModel (pass `cudnn` as a second argument.

**Comment by liuchang8am** [comment]
Thanks! Load in cudnn mode solves the error.
