### ISSUE TITLE
model.lua no zeiler.t7

### ISSUE THREAD

**Issue by northeastsquare** [fmassa/object-detection.torch#2]
Hello, I run: th main.lua, get the following error. So where is the the zeiler.t7 file? Thanks

/home/silva/torch/install/bin/luajit: cannot open <data/models/zeiler.t7> in mode r  at /home/silva/torch/pkg/torch/lib/TH/THDiskFile.c:484
stack traceback:
    [C]: at 0x7fc61fa65470
    [C]: in function 'DiskFile'
    /home/silva/torch/install/share/lua/5.1/torch/File.lua:292: in function 'load'
    /home/silva/src/object-detection.torch/model.lua:7: in main chunk
    [C]: in function 'dofile'
    main.lua:32: in main chunk
    [C]: in function 'dofile'
    ...ilva/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406670

**Comment by northeastsquare** [comment]
Is this https://github.com/ShaoqingRen/SPP_net/blob/master/model-defs/Zeiler_conv5.prototxt

**Comment by fmassa** [comment]
I indeed took the pretrained models from there, that contain the conv layers and the linear layers. I used a variant of loadcaffe to load it in torch format. I'll put this model online and update the README this weekend.

**Comment by northeastsquare** [comment]
Thank you, you are so kind.

**Comment by fmassa** [comment]
@northeastsquare this should be addressed in https://github.com/fmassa/object-detection.torch/commit/1ac9fa097666d3d12aa462018c9dd006ffccfe17
Let me know if you have any troubles using the code.
