### ISSUE TITLE
Assertion `THCudaTensor_nDimension(state, data) == 4' failed

### ISSUE THREAD

**Issue by capuzz** [fmassa/object-detection.torch#25]
Hi, I'm trying to work with 'alexnet' for fast-rcnn but I have this error:

> In 2 module of nn.Sequential:
> /home/torch/install/share/lua/5.1/inn/ROIPooling.lua:26: Assertion `THCudaTensor_nDimension(state, data) == 4' failed.  at /tmp/luarocks_inn-1.0-0-334/imagine-nn/ROIPooling.cu:184
> stack traceback:
> 	[C]: in function 'inn_ROIPooling_updateOutputV2'
> 	/home/torch/install/share/lua/5.1/inn/ROIPooling.lua:26: in function </home/torch/install/share/lua/5.1/inn/ROIPooling.lua:20>
> 	[C]: in function 'xpcall'
> 	/home/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
> 	/home/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
> 	./Trainer.lua:73: in function 'opfunc'
> 	/home/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
> 	./Trainer.lua:87: in function 'train'
> 	...nia//3a/object-detection.torch-refactoring/train.lua:29: in main chunk
> 	[C]: in function 'dofile'
> 	main.lua:42: in main chunk
> 	[C]: in function 'dofile'
> 	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50

I don't understand which kind of error is this and how I can fix it.
Thanks

**Comment by fmassa** [comment]
you need to pass a 4d tensor for the input, in the format (batch, channels, height, width).
