### ISSUE TITLE
Cannot run main.lua

### ISSUE THREAD

**Issue by szagoruyko** [fmassa/object-detection.torch#4]
```
=> Criterion
nn.CrossEntropyCriterion
==> Converting model to CUDA
/opt/rocks/distro/install/bin/luajit: [string "argcheck"]:9237:
A dataset class for object detection in Pascal-like datasets.

invalid arguments!
stack traceback:
    [C]: in function 'error'
    [string "argcheck"]:9237: in function 'initcheck'
    ./DataSetPascal.lua:106: in function '__init'
    /opt/rocks/distro/install/share/lua/5.1/torch/init.lua:54: in function </opt/rocks/distro/install/share/lua/5.1/torch/init.lua:50>
    [C]: in function 'DataSetPascal'
    /tmp/object-detection.torch/data.lua:32: in main chunk
    [C]: in function 'dofile'
    main.lua:33: in main chunk
    [C]: in function 'dofile'
    ...cks/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406170
```

**Comment by fmassa** [comment]
@szagoruyko you probably don't have a valid path to de dataset `datadir`, and the weird error message comes from a problem with `argcheck`. You should probably check that the argument option `-datadir` contains a folder `VOC2007` in it.

**Comment by szagoruyko** [comment]
yeah this is probably due to relative paths. Closing, but there has to be a check for that I think, someone could scratch his head for a while.

**Comment by fmassa** [comment]
There is, check https://github.com/fmassa/object-detection.torch/blob/master/DataSetPascal.lua#L47 . The problem is due to a bug in `argcheck`, which is not outputting the good error message...

**Comment by fmassa** [comment]
Actually, I found why it's not printing the help. I'll fix it
